# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pato Lankenau Blog
email: contact@p.lankenau.io
description: > # this means to ignore newlines until "baseurl:"
  Software Engineer that works in distributed systems.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://plankenau.com" # the base hostname & protocol for your site
github_username:  pato

# Build settings
markdown: kramdown
